#!/usr/bin/env ruby

require 'sass'
require 'haml'
require 'json'
require 'maruku'
require 'sinatra'

HERE = Pathname.new(__FILE__) + '..'
set :public_folder, File.dirname(__FILE__)

class Photo
  attr_reader :id

  def initialize(root, id)
    @root = root
    @id = id
  end

  def link
    "/#@root/#@id"
  end

  def original_url
    "/" + Dir[HERE + "#@root/#@id/photo_o.*"].first.gsub(/\A#{HERE.to_s}\//, '')
  end

  def thumbnail_url
    "/" + Dir[HERE + "#@root/#@id/photo_z.*"].first.gsub(/\A#{HERE.to_s}\//, '')
  end

  def data
    @data ||= JSON.parse(File.read(HERE + "#@root/#@id/data.json"))
  end

  def method_missing(sym, *args, &block)
    if data.key?(sym.to_s)
      data[sym.to_s]
    else
      super
    end
  end
end

class User
  attr_reader :id, :name

  def initialize(id, name)
    @id, @name = id, name
  end

  def url
    "/photos/#{id}"
  end

  def photos
    Dir[HERE + "#{url[1..-1]}/*"].reverse.map {|path|
      Photo.new(url[1..-1], path.split("/").last.to_i)
    }
  end

  def photo(id)
    photos.find {|ph| ph.id == id.to_i }
  end
end

get '/photos/:user_id' do
  @user = User.new(params[:user_id], "hawx~")
  @photos = @user.photos.take(5)
  haml :stream
end

get '/photos/:user_id/:photo_id' do
  @user = User.new(params[:user_id], "hawx~")
  @photo = @user.photo(params[:photo_id])
  haml :show
end

get '/styles.css' do
  sass :styles
end
