#!/usr/bin/env ruby

require 'nokogiri'
require 'digest/md5'
gem 'sass'; require 'sass'
require 'haml'
require 'sinatra'
require 'json'
require 'time'
require 'pathname'
require 'seq'
require 'seq/pager'

PAGE_SIZE = 10
HERE = Pathname.new(__FILE__) + '..'
set :views, File.dirname(__FILE__) + '/app'


def format_time(str)
  Time.parse(str).strftime('%d %B %Y')
end

class Post
  def initialize(user, id)
    @user = user
    @id = id
  end

  def name
    data['title']
  end

  def path
    @user.path + 'posts' + @id
  end

  def id
    data['id']
  end

  def data
    @data ||= JSON.parse(File.read(path + "data.json"))
  end

  def url
    @user.url + '/post/' + @id
  end

  def resource_path(url)
    "/resource/#{@user.name}/#{id}/" + (Digest::MD5.hexdigest(url) + File.extname(url))
  end

  def fix_resources(text)
    doc = Nokogiri::HTML(text)
    resources = doc.xpath('//img/@src').map(&:value)

    resources.each do |resource|
      text = text.gsub resource, resource_path(resource).to_s
    end

    text
  end

  def method_missing(sym, *args)
    if data.has_key?(sym.to_s)
      return data[sym.to_s]
    end

    if sym.to_s.end_with?('?')
      return data.has_key?(sym[0..-2].to_s) && !data[sym[0..-2].to_s].empty?
    end

    super
  end
end

class User
  def self.all
    Dir[HERE + '*/'].reject {|path|
      path.end_with?('/app/')
    }.map {|path|
      new(path.split("/").last)
    }
  end

  def initialize(name)
    @name = name
  end

  def data
    @data ||= JSON.parse(File.read(path + "data.json"))
  end

  def name
    data['name']
  end

  def path
    HERE + @name
  end

  def url
    '/' + @name
  end

  def find(post_id)
    posts.find {|post| post.id == post_id.to_i }
  end

  def posts
    @posts ||= Dir[path + 'posts' + '*']
      .map {|p| Post.new(self, p.split('/').last) }
      .sort_by {|p| p.data['id']}
      .reverse
  end

  def __pages
    @pages ||= Seq::Pager.new(PAGE_SIZE, posts)
  end

  def page(num)
    __pages.page = num
    __pages.curr
  end

  def pages
    __pages.pages
  end

  def range
    __pages.range(2, 2, 2)
      .reject(&:empty?)
      .map {|a| a << nil }
      .flatten.tap(&:pop)
  end
end


get '/styles.css' do
  sass :styles
end

get '/' do
  @users = User.all

  haml :index
end

get '/:user/?' do
  @user  = User.new(params[:user])
  @page  = 0
  @posts = @user.page(@page)

  haml :list
end

get '/:user/page/:num/?' do
  redirect "/#{params[:user]}" if params[:num] == "0"

  @user  = User.new(params[:user])
  @page  = params[:num].to_i
  @posts = @user.page(@page)

  haml :list
end

get '/resource/:user/:post/:resource/?' do
  path = HERE + params[:user] + 'posts' + params[:post] + params[:resource]
  File.read(path)
end

get '/:user/post/:id/?' do
  @user = User.new(params[:user])

  @post = @user.find(params[:id])
  return "No post found" unless @post

  @posts = [@post]

  haml :list
end
