#!/usr/bin/env ruby

gem 'sass'; require 'sass'
require 'haml'
require 'sinatra'
require 'json'
require 'time'
require 'pathname'
require 'seq'
require 'seq/pager'

PAGE_SIZE = 10
HERE = Pathname.new(__FILE__) + '..'
set :views, File.dirname(__FILE__) + '/app'


def format_time(str)
  Time.parse(str).strftime('%d %B %Y')
end

class Post
  def initialize(user, id)
    @user = user
    @id = id
  end

  def path
    @user.path + 'posts' + @id
  end

  def data
    @data ||= JSON.parse(File.read(path + "data.json"))
  end

  def url
    @user.url + '/post/' + @id
  end
end

class User
  def initialize(name)
    @name = name
  end

  def path
    HERE + @name
  end

  def url
    '/' + @name
  end

  def posts
    @posts ||= Dir[path + 'posts' + '*']
      .map {|p| Post.new(self, p.split('/').last) }
      .sort_by {|p| p.data['id']}
      .reverse
  end

  def __pages
    @pages ||= Seq::Pager.new(PAGE_SIZE, posts)
  end

  def page(num)
    __pages.page = num
    __pages.curr
  end

  def pages
    __pages.pages
  end

  def range
    __pages.range(2, 2, 2)
      .reject(&:empty?)
      .map {|a| a << nil }
      .flatten.tap(&:pop)
  end
end


get '/styles.css' do
  sass :styles
end

get '/:user/?' do
  @user  = User.new(params[:user])
  @page  = 0
  @posts = @user.page(@page)

  haml :list
end

get '/:user/page/:num/?' do
  redirect "/#{params[:user]}" if params[:num] == "0"

  @user  = User.new(params[:user])
  @page  = params[:num].to_i
  @posts = @user.page(@page)

  haml :list
end

get '/:user/post/:id/?' do
  @user = User.new(params[:user])

  @post = @user.find(params[:id])
  return "No post found" unless @post

  haml :post
end
